### ISSUE TITLE
Symbol not found on Apple Silicon

### ISSUE THREAD

**Issue by yukinarit** [yukinarit/apnggif#4]
```
(line-stamp) yukinari@mac~/r/line-stamp> python line.py --help
Traceback (most recent call last):
  File "/Users/yukinari/repos/line-stamp/line.py", line 8, in <module>
    from apnggif import apnggif
  File "/Users/yukinari/.local/share/virtualenvs/line-stamp-ahb8wv1F/lib/python3.9/site-packages/apnggif.py", line 1, in <module>
    import apnggif_sys
ImportError: dlopen(/Users/yukinari/.local/share/virtualenvs/line-stamp-ahb8wv1F/lib/python3.9/site-packages/apnggif_sys.cpython-39-darwin.so, 2): Symbol not found: _png_init_filter_functions_neon
  Referenced from: /Users/yukinari/.local/share/virtualenvs/line-stamp-ahb8wv1F/lib/python3.9/site-packages/apnggif_sys.cpython-39-darwin.so
  Expected in: flat namespace
 in /Users/yukinari/.local/share/virtualenvs/line-stamp-ahb8wv1F/lib/python3.9/site-packages/apnggif_sys.cpython-39-darwin.so
```

🤔

**Comment by sungkhum** [comment]
Same here - no fix yet...

**Comment by yukinarit** [comment]
UPDATE: I've pushed the 0.1.3 with the wheel built for M1 Mac  but got the same error.

I will look into 
* https://github.com/deepmind/lab2d/issues/5
* https://www.ridgesolutions.ie/index.php/2014/02/05/cross-compiling-libpng-for-arm-linux-with-neon-and-zlib/
